name: Check IDE Compatibility

on:
  schedule:
    - cron: '55 2 * * 1'
  workflow_dispatch:

jobs:
  check-ide-compatibility:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17]
        distribution: [temurin]
        platformType: [IC]
        platformVersion: [LATEST-EAP-SNAPSHOT]

    steps:
    - name: Free up disk space
      run: |
        df -h
        docker system prune -af
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Diagnose memory problems
      run: sudo du --max-depth=2 /usr/ | sort -r -k1,1n

    - uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
      
    # - name: Check compatibility
    #   run: ./gradlew runPluginVerifier -PplatformVersion=LATEST-EAP-SNAPSHOT --info
