name: Check IDE Compatibility

on:
  schedule:
    - cron: '55 2 * * 1'
  workflow_dispatch:

jobs:
  check-ide-compatibility:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17]
        distribution: [temurin]
        platformType: [IC]
        platformVersion: [LATEST-EAP-SNAPSHOT]

    steps:
    - name: Diagnose memory problems
      run: du --max-depth=4 / | sort -r -k1,1n

    - uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'gradle'
      
    - name: Build
      run: ./gradlew runPluginVerifier -PplatformVersion=LATEST-EAP-SNAPSHOT --info
